[pytest]
testpaths = tests
markers =
    smoke: Smoke tests
    regression: Regression tests
    ui: UI tests
    api: API tests
    login: Login related tests
    inventory: Inventory related tests
addopts =
    --strict-markers
    --tb=short
    -v
